### ISSUE TITLE
Nginx Cache Purge

### ISSUE THREAD

**Issue by DPCools** [nexusofdoom/lancache-installer#1]
the install-nginx.sh line below does not work as it looks to be no longer there.
if you have the file could it be put in to Box  or dropbox so it can be downloaded.

#Get Nginx Cache Purge from Frickle Labs:
curl "http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz" | tar zx

**Comment by DPCools** [comment]
when i did get a copy of the file to download it now gets stuck at 

Installing with make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by nexusofdoom** [comment]
just tested the file is still online and it did pull down.
![image](https://user-images.githubusercontent.com/16519553/40486926-437da410-5f28-11e8-9674-b513537ca2b5.png)

**Comment by nexusofdoom** [comment]
you are running Debian 9.4  x64?

**Comment by nexusofdoom** [comment]
you also did this before you ran the other install.sh file?

git clone -b master http://github.com/nexusofdoom/lancache-installer

cd lancache-installer

chmod +x *.sh

#Run scripts as sudo or root user

#Run

./install.sh

#Next run

./install-jemalloc.sh

#Then run

./install-nginx.sh

**Comment by DPCools** [comment]
I was following the on screen instructions.

**Comment by nexusofdoom** [comment]
I would try again it worked for me fresh install on new vm debian 9.4 64bit 

![image](https://user-images.githubusercontent.com/16519553/40509505-5f4f770e-5f5f-11e8-880e-73184150b3f5.png)

**Comment by nexusofdoom** [comment]
once all done rebooted and services working 
![image](https://user-images.githubusercontent.com/16519553/40509618-bea7ec90-5f5f-11e8-8b38-3c605aed9df4.png)

**Comment by DPCools** [comment]
I will give it another try.

**Comment by DPCools** [comment]
So the install looks to have worked this time. 

In file install-lancache.sh line  25 and 53  ------------------------------------ 
you might want to rem them out  
./install-lancache.sh: line 53: ---------------------------------------------------------------------------------------------: command not found
./install-lancache.sh: line 25: ---------------------------------------------------------------------------------------------: command not found

**Comment by nexusofdoom** [comment]
Sounds good closing this ticket.
