### ISSUE TITLE
lancache keeps downloading

### ISSUE THREAD

**Issue by jsnepo** [nexusofdoom/lancache-installer#10]
I'm monitoring my incoming bandwidth after it lancache is triggered by an update on PS4.  Update is just around 1GB and my Internet connection is at a 100Mbps.

Five minutes after, lancache is still downloading something. It's taking up a huge space in my HDD already.  It's just 1GB but so far the download has taken around 10GB.  What seems to be the problem? It was working last week.

**Comment by nexusofdoom** [comment]
On lancach box use httpry on interface and see what it's downloading. It
could be windows updates or other services asking for updates

**Comment by jsnepo** [comment]
This time cache isn't being triggered.  Downloads goes directly to the PS4.  Doing HTTPRY does detect activity but cache isn't working.

**Comment by nexusofdoom** [comment]
what does the log show? does it say its not working in the log?

**Comment by jsnepo** [comment]
Where do you find it? I have to say I'm pretty new with Linux.

**Comment by nexusofdoom** [comment]
the logs are in /srv/lancache/logs/Keys or Logs or Access

**Comment by jsnepo** [comment]
Found Keys and Access. Checked sony.log.

Logs only refer to sony/networktest/ and there's a bunch of cache and a bunch miss.

**Comment by nexusofdoom** [comment]
if that is the case the PS4 is not looking at the cache but is pulling direct. 
do you have the domains its downloading from and or IP address it's using that you can pull from the firewall.

**Comment by nexusofdoom** [comment]
this is the list of domains we have for sony - if sony is now using more domains the list will need to be updated.

## Sony °|-lc-host-vint:6
        local-zone: "pls.patch.station.sony.com." redirect
        local-data: "pls.patch.station.sony.com. 600 IN A lc-host-sony"
        local-zone: "playstation.net." transparent
        local-zone: "gs2.ww.prod.dl.playstation.net." redirect
        local-data: "gs2.ww.prod.dl.playstation.net. 600 IN A lc-host-sony"
        local-zone: "gs2.sonycoment.loris-e.llnwd.net." redirect
        local-data: "gs2.sonycoment.loris-e.llnwd.net. 600 IN A lc-host-sony"

**Comment by jsnepo** [comment]
gs2.ww.prod.dl.playstation.net

It's the same domain as before and was working. Why is not working now?

**Comment by nexusofdoom** [comment]
no clue why its not working I would have to see the logs on the lancache , firewall and run wireshark on the network to see what is going on.

I do not have a PS4 to test on my side.

**Comment by jsnepo** [comment]
Okay. I may try to reinstall lancache on a clean Ubuntu server and see what happens.  By the way, is there a way to edit the list of domains above?  I also would like to know if I the IP address for the domains above are set specifically somewhere in lancache and if I can edit them?  I've found CDN IP addresses that work best in my region and would like to use them instead.

**Comment by nexusofdoom** [comment]
if you want to add you need to add to file /etc/unbound/unbound.conf

**Comment by jsnepo** [comment]
Got it.  I got one more.  Where in lancache can I edit the host for Sony downloads?  For example the domain gs2.ww.prod.dl.playstation.net... I want this to get downloads from 122.2.209.48 and 122.2.209.27. Where do I configure this?

**Comment by nexusofdoom** [comment]
You need a host name, try and use wireshark and see what the host names  are for the IP's

**Comment by nexusofdoom** [comment]
some information on that ip range 
https://www.proxydocker.com/en/proxy/122.2.209.1

**Comment by nexusofdoom** [comment]
found this 
http://www.psdevwiki.com/ps4/PKG_files/rawlist1

**Comment by nexusofdoom** [comment]
try pinging this domain and what ip do you get?
ic.ae179e00.11a2c5.gs2.sonycoment.loris-e.llnwd.net

**Comment by jsnepo** [comment]
It changes. Right now it's 38.98.18.178.


By the way, I did some downloads and was able to complete them.  But when I switched to another device, the cache somehow downloads the games again.  I thought I already completed it.

**Comment by jsnepo** [comment]
I've noticed that this happens when the CDN IP changes from what the content was downloaded before thus triggering another download.  Is there anyway we can specify the following hosts; gs2.ww and gs2.loris-e to download from a fixed CDN IP?

**Comment by nexusofdoom** [comment]
please log httpry when you are downloading. 
I need more information.  if you download the game on gs2.ww.prod.dl.playstation.net
then you download again the same game and it pulls from gs2.sonycoment.loris-e.llnwd.net
we may need to blackhole the a domain and test but I need to see how "httpry" looks like in a log

**Comment by jsnepo** [comment]
Yes, sorry. I did run httpry but without logs.  Also downloads coming from gs2.sonycoment.loris-e.llnwd.net are really slow so directing it to a better CDN will also help.  I tried editing the hosts file under ETC to resolve gs2.ww.prod.dl.playstation.net and gs2.sonycoment.loris-e.llnwd.net to 122.2.209.48 and 122.2.209.27 but to no avail.

I will try again to download.  I've set this for NBA 2K19 which is around 54GB so completing it will take some time.  For now do you have ideas how to configure lancache to download using the domains given but resolving to my specified CDN IP addresses?

**Comment by nexusofdoom** [comment]
you would need to tell nginx to use a dns server that has the static info for the domain to ip you want to use, the issue would be if that IP changes or they take that server offline since you are telling it to direct connect to that one IP for updates. the file to edit to tell nginx to use would be "nginx.conf"

**Comment by mastertryce** [comment]
I actually spent a wohle day , downloaded over 100 games and deleted them to download them agan and juggled with httpry and nslookup to find all of sony's loadbalancer domains.
I think i found most of them, caching now works most of the time, exept the loadbalancer chose to use a level3 server, the server will respond to the ps4 with a direct ip adress, the ip adress will be a different every time you are conected to a level3 server.

       local-zone: "pls.patch.station.sony.com." redirect
       local-data: "pls.patch.station.sony.com. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "playstation.net." transparent
       local-zone: "gs2.ww.prod.dl.playstation.net." redirect
       local-data: "gs2.ww.prod.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "gs2.sonycoment.loris-e.llnwd.net." redirect
       local-data: "gs2.sonycoment.loris-e.llnwd.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "theia.dl.playstation.net." redirect
       local-data: "theia.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "tmdb.np.dl.playstation.net." redirect
       local-data: "tmdb.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "gs-sec.ww.np.dl.playstation.net." redirect
       local-data: "gs-sec.ww.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "playstation4.sony.akadns.net." redirect
       local-data: "playstation4.sony.akadns.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "gs2-ww-prod.psn.akadns.net." redirect
       local-data: "gs2-ww-prod.psn.akadns.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "gs2.ww.prod.dl.playstation.net.edgesuite.net." redirect
       local-data: "gs2.ww.prod.dl.playstation.net.edgesuite.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "*.cloudfront.net." redirect
       local-data: "*.cloudfront.net. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "*.deploy.static.akamaitechnologies.com." redirect
       local-data: "*.deploy.static.akamaitechnologies.com. 30 IN A YOUR-IP-ADDRESS"
       local-zone: "*.llnw.net." redirect
       local-data: "*.llnw.net. 30 IN A YOUR-IP-ADDRESS"
