### ISSUE TITLE
PiHole with lancache

### ISSUE THREAD

**Issue by nexusofdoom** [nexusofdoom/lancache-installer#16]
for my setup 
i have an extra ip that PiHole binds to and i edit sniproxy so it only binds to the services ip's for nginx.

**Comment by cruelviper** [comment]
i am iterested where did you change things to be able to use pihole too?

**Comment by nexusofdoom** [comment]
install pie-hole and inside of pie-hole point to unbound dns.

need to stop unbound and nginx and install pie-hole then edit the configs for pie-hole to bind to extra IP that nginx and ubnound is not using.

**Comment by nexusofdoom** [comment]
I needed to bind sniproxy to each of the nginx services along with unbound then I also had to modify PiHole to bind a spare IP not used by unbound, sniproxy or nginx.
