### ISSUE TITLE
Add variable in the installer for cache size for services.

### ISSUE THREAD

**Issue by nexusofdoom** [nexusofdoom/lancache-installer#17]
max_size=100000m  in  /etc/nginx/lancache/caches  that would be nice to have a variable in the installer that some on can change for there storage sizes?

**Comment by picchioni** [comment]
The problem with this is near as I can tell you can't have a cumulative max_size for all of the proxy_cache_path options. Which means if you set all of them to 100000m and your HD Capacity is only 100GB, each cache is going to try to populate 100GB worth of data when in reality the cumulative of all the caches shouldn't be 100GB. Is there a way to have nginx see all of them as one calculation?

**Comment by nexusofdoom** [comment]
so in my setup I know I have 8 services that I want to cache and I want all 8 to have 500 GB each so the storage drive needs to have space for 4TB of data. end user needs to know how much space they need.

**Comment by picchioni** [comment]
Agreed, if they're aware of that fact then it shouldn't be a problem

**Comment by nexusofdoom** [comment]
closing this issue updated.
