### ISSUE TITLE
Better instructions?

### ISSUE THREAD

**Issue by jarredwalton** [nexusofdoom/lancache-installer#2]
I realize Github probably isn't the place to ask for better instructions, but I'm going to request some help regardless. I'm hoping to put together something of a "newb guide" for this whole process. My planned setup goes like this:

Cable-modem -> Lancache PC -> WiFi/router

The PC is far more powerful than this likely needs, but it has the advantage of already having two GbE ports. But... it doesn't seen to want to work. I have the Intel NUC with i7-8809G, and after installing Debian, the boot process fails with ACPI and WiFi error messages. Or at least, it just stops.

Maybe I didn't install a desktop manager properly? Maybe the chip isn't supported? Anyway, I did Ctrl+Alt+F2 to switch windows, logged in as root, and followed the rest of your script. So far so good, though it would be nice to have it auto-boot into the text console and have lancache running if nothing else. Maybe it does?

ifconfig shows something like 15 different network connections, but they're all from my existing router since it's configured like this right now:

Cable-modem -> WiFi/router -> Lancache PC

I guess I just need to swap the position of the router and Lancache system, but then probably do some other stuff. Specifically, I want the Lancache PC to get an IP from the modem, and then I want the router to get an IP address from the PC, and then... everything should work!? Do I just run change-network.sh to specify IP ranges?

Feel free to email me at jarred [at] pcgamer [dot] com to discuss further. I'm hoping to post something of a short writeup of the process and any final steps that I need to take, so that others can easily copy the work.

**Comment by nexusofdoom** [comment]
Checking on status do you still need help setting up?
