### ISSUE TITLE
Flush cached items.

### ISSUE THREAD

**Issue by SniperkroZ** [nexusofdoom/lancache-installer#25]
Hi, is there any way to flush certain steam games? i have an issue where one of the games will slow down to 50kb/s in the last 200mb and not download. Logs state timeouts to steam. When i switch off the cache it will download the last 200mb fine over the open internet.

Or is it an issue where the steam hosts need updating?

**Comment by nexusofdoom** [comment]
this is what I am have in my home config 
I would check and see I added a few domains for testing last week.
let me know if this list works for you, note you will need to change the IP  to match what your setup is for /etc/unbound/unbound.conf

    ## LANcache config ##
    
## Steam °|-lc-host-vint:1
        local-zone: "steampowered.com." transparent
        local-zone: "steamcdn-a.akamaihd.net.edgesuite.net." redirect
        local-data: "steamcdn-a.akamaihd.net.edgesuite.net. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "client-download.steampowered.com." redirect
        local-data: "client-download.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content-origin.steampowered.com." redirect
        local-data: "content-origin.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "steam-content-dnld-1.apac-1-cdn.cqloud.com." redirect
        local-data: "steam-content-dnld-1.apac-1-cdn.cqloud.com. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "steampipe-kr.akamaized.net." redirect
        local-data: "steampipe-kr.akamaized.net. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "steam.naeu.qtlglb.com.cdn20.com." redirect
        local-data: "steam.naeu.qtlglb.com.cdn20.com. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "steam.eca.qtlglb.com." redirect
        local-data: "steam.eca.qtlglb.com. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "steam.ix.asn.au." redirect
        local-data: "steam.ix.asn.au. 30 IN A YOUR-IP-ADDRESS"
	local-zone: "content1.steampowered.com." redirect
        local-data: "content1.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content2.steampowered.com." redirect
        local-data: "content2.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content3.steampowered.com." redirect
        local-data: "content3.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content4.steampowered.com." redirect
        local-data: "content4.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content5.steampowered.com." redirect
        local-data: "content5.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content6.steampowered.com." redirect
        local-data: "content6.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content7.steampowered.com." redirect
        local-data: "content7.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "content8.steampowered.com." redirect
        local-data: "content8.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "cs.steampowered.com." redirect
        local-data: "cs.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "akamai.steamtransparent.com." redirect
        local-data: "akamai.steamtransparent.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "hsar.steampowered.com.edgesuite.net." redirect
        local-data: "hsar.steampowered.com.edgesuite.net. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "steamcontent.com." redirect
        # local-data: "steampipe.steamcontent.com. 30 IN A YOUR-IP-ADDRESS"
        local-data: "steamcontent.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "edgecast.steamstatic.com." redirect        
        local-data: "edgecast.steamstatic.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "steampipe.akamaized.net." redirect
        local-data: "steampipe.akamaized.net. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "steam.apac.qtlglb.com." redirect
        local-data: "steam.apac.qtlglb.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "steam.apac.qtlglb.com.mwcloudcdn.com." redirect
        local-data: "steam.apac.qtlglb.com.mwcloudcdn.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "cdn1-sea1.valve.net." redirect
        local-data: "cdn1-sea1.valve.net. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "cdn2-sea1.valve.net." redirect
        local-data: "cdn2-sea1.valve.net. 30 IN A YOUR-IP-ADDRESS"
        # Refuse for Comcast CDN Issues   
        local-zone: "edge.steam-dns.top.comcast.net." refuse
        local-zone: "edge.steam-dns-2.top.comcast.net." refuse 
        local-zone: "steamcdn-a.akamaihd.net." redirect
        local-data: "steamcdn-a.akamaihd.net. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "media4.steampowered.com." redirect
        local-data: "media4.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "media2.steampowered.com." redirect
        local-data: "media2.steampowered.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "akamai.steamstatic.com." redirect
        local-data: "akamai.steamstatic.com. 30 IN A YOUR-IP-ADDRESS"
        local-zone: "steam.naeu.qtlglb.com." redirect
        local-data: "steam.naeu.qtlglb.com. 30 IN A YOUR-IP-ADDRESS"

**Comment by SniperkroZ** [comment]
Thanks, ill add what is missing from mine and test again.

FYI here is the errors in /srv/lancache/logs/errors/steam.log

2018/12/31 23:32:44 [error] 932#932: *16988 valve409.steamcontent.com could not be resolved (110: Operation timed out), client: 172.10.0.105, server: steam, request: "GET /server-status HTTP/1.1", host: "valve409.steamcontent.com"
2018/12/31 23:33:48 [error] 932#932: *16988 valve549.steamcontent.com could not be resolved (110: Operation timed out), client: 172.10.0.105, server: steam, request: "GET /server-status HTTP/1.1", host: "valve549.steamcontent.com"
2018/12/31 23:34:34 [error] 932#932: *16988 valve559.steamcontent.com could not be resolved (110: Operation timed out), client: 172.10.0.105, server: steam, request: "GET /server-status HTTP/1.1", host: "valve559.steamcontent.com"
