### ISSUE TITLE
Ip configuration

### ISSUE THREAD

**Issue by marol94** [nexusofdoom/lancache-installer#27]
i don't understand if i need to setup the other ip address manually or if the script autoconfigure the ip

**Comment by nexusofdoom** [comment]
It will auto populate the other ip's in the interface file automatically.

**Comment by marol94** [comment]
ok, so if the bare machine is on the 0.1, the script will automatically bind the other ip like 0.2-0.18 right?
on a freshly installed 18.04 server, i need only to launch the script, wait, and point the client to the bare metal pc ip right?

**Comment by nexusofdoom** [comment]
reinstall using 18.04.1 
http://cdimage.ubuntu.com/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso
