### ISSUE TITLE
Tmp folder

### ISSUE THREAD

**Issue by chalhoub37** [nexusofdoom/lancache-installer#29]
Hello what ia the tmp folder in lancache data ?? It is always downloading and getting bigger when i am not even doing anything

**Comment by nexusofdoom** [comment]
I would try this and see what it's downloading 


http://xmodulo.com/sniff-http-traffic-command-line-linux.html

**Comment by chalhoub37** [comment]
I already sniff the http and nothing os downloading .. btw how big is the slice for file to cache ? If i am downloading a game how big is the caching file before it end downloading ?

**Comment by nexusofdoom** [comment]
https://github.com/nexusofdoom/lancache-installer/blob/master/etc/nginx/lancache/caches

**Comment by nexusofdoom** [comment]
so you say noting downloading over http then it should not be downloading via nginx then some other process is downloading to the tmp folder then.
since nginx is only setup to download and cache using http.

**Comment by chalhoub37** [comment]
So the number next to the cache_key name is the slice setting ?? Am i right ? And can i change this to a lower number ??

**Comment by nexusofdoom** [comment]
max_size= change to the size you are looking for.

**Comment by nexusofdoom** [comment]
what size are you looking to change?

**Comment by chalhoub37** [comment]
The slice size like how big is the single cached file bcz i have a bad internet and when the slice file is big sometime the doing get corrupted with nginx u have slice size like if i am downloading something it will cache every 10mb , 20mb so if i restart the download it will have cache most of it sorry my bad english cant explain better hope u get what i mean

**Comment by nexusofdoom** [comment]
you would need to edit this 
lancache-installer/etc/nginx/lancache/cache-slice

slice 16777216; to what size you want it to use.

**Comment by chalhoub37** [comment]
And this is in byte ?

**Comment by nexusofdoom** [comment]
correct.
