### ISSUE TITLE
Change cache file storage location

### ISSUE THREAD

**Issue by mrdeadlocked** [nexusofdoom/lancache-installer#31]
Where would I go about changing the location that all of the cached files get saved?

**Comment by nexusofdoom** [comment]
check this file out.
/etc/nginx/lancache/caches

**Comment by mrdeadlocked** [comment]
Nice! I see that. Can I update the installer so that it installs directly into a different path? instead of updating all of those entries? WOuld changing the directory below hurt anything else? or is it better to just edit the file you suggested after the fact.

# File path for lancache
lc_srv_loc="/srv/lancache"

**Comment by mrdeadlocked** [comment]
I got it all set up on a proxmox container using your script. My lancache directory is on a ZFS file store. :-) Thanks so much!

**Comment by nexusofdoom** [comment]
In Linux you can change in fstab the mount points over editing the /etc/nginx/lancache/caches.

**Comment by cdoublejj** [comment]
how would one leverage the fstab in that way?
