### ISSUE TITLE
League Of Legends unable to login

### ISSUE THREAD

**Issue by mrdeadlocked** [nexusofdoom/lancache-installer#32]
Using this cache I am able to use steam/battle.net without issues. I finally sat down to try out league and I am unable to login game says that I am offline on client. If I revert DNS back to a public DNS I can log right in. What do you need from me?

**Comment by mrdeadlocked** [comment]
I got it. I'm an idiot. :-)

**Comment by tu0mas** [comment]
Can you explain what you did in order to resolve the problem? Thank you.
