### ISSUE TITLE
Blizzard slow download

### ISSUE THREAD

**Issue by RobertJamesMichael** [nexusofdoom/lancache-installer#33]
Hi, I've been testing the installer, and blizzard is downloading very slow on new downloads, maybe adding some ips is the solution, but, is there another way, because there are too many ips configured, 10 for steam for example...
Also would be good to update the installer to have Epic included, thanks

**Comment by nexusofdoom** [comment]
I have updated the installer to add more IPs just like steam is doing now for Blizzard I also added EPIC to the installer along with an updated NGINX version and fixed a bug with ubuntu unboud service.

**Comment by nexusofdoom** [comment]
looks all good on my side going to close the ticket.
