### ISSUE TITLE
IP Adresses

### ISSUE THREAD

**Issue by RobertJamesMichael** [nexusofdoom/lancache-installer#34]
Hi, the script to populate the IP address beginning from 192.168.24.10 is creating the file:

network:
 version: 2
 renderer: networkd
 ethernets:
   ens33:
     dhcp4: no
     dhcp6: no
     addresses: [192.168.24.10/24]
     addresses: [192.168.24.20/24]
     addresses: [192.168.24.20/242]
     addresses: [192.168.24.20/243]
     addresses: [192.168.24.20/244]
     addresses: [192.168.24.20/245]
     addresses: [192.168.24.20/246]
     addresses: [192.168.24.20/247]
     addresses: [192.168.24.20/248]
     addresses: [192.168.24.20/249]
     addresses: [192.168.24.20/2410]
     addresses: [192.168.24.19/24]
     addresses: [192.168.24.13/24]
     addresses: [192.168.24.14/24]
     addresses: [192.168.24.18/24]
     addresses: [192.168.24.21/24]
     addresses: [192.168.24.17/24]
     addresses: [192.168.24.22/24]
     addresses: [192.168.24.15/24]
     addresses: [192.168.24.11/24]
     addresses: [192.168.24.12/24]
     addresses: [192.168.24.23/24]
     addresses: [192.168.24.24/24]
     addresses: [192.168.24.16/24]
     addresses: [192.168.24.25/24]
     addresses: [192.168.24.26/24]
     addresses: [192.168.24.27/24]
     gateway4: 192.168.24.253
     nameservers:
       addresses: [8.8.8.8,4.2.2.2]

 I am using a clean 18.04 installation

**Comment by nexusofdoom** [comment]
are you using this version of 18.04 ?
Download url for Ubuntu 18.04.1 Server
http://cdimage.ubuntu.com/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso

and your network interface is setup as dhcp?
 it will switch to static once you run the script.

**Comment by RobertJamesMichael** [comment]
ok, I am using that version (18.04.1) but I am not using DHCP, I will try that ASAP. thanks!

**Comment by RobertJamesMichael** [comment]
Hi, I tried on a clean 18.04.1 server using DHCP, results:
network:
 version: 2
 renderer: networkd
 ethernets:
   ens33:
     dhcp4: no
     dhcp6: no
     addresses: [192.168.24.10/24]
     addresses: [192.168.24.20/24]
     addresses: [192.168.24.20/242]
     addresses: [192.168.24.20/243]
     addresses: [192.168.24.20/244]
     addresses: [192.168.24.20/245]
     addresses: [192.168.24.20/246]
     addresses: [192.168.24.20/247]
     addresses: [192.168.24.20/248]
     addresses: [192.168.24.20/249]
     addresses: [192.168.24.20/2410]
     addresses: [192.168.24.19/24]
     addresses: [192.168.24.13/24]
     addresses: [192.168.24.14/24]
     addresses: [192.168.24.18/24]
     addresses: [192.168.24.21/24]
     addresses: [192.168.24.17/24]
     addresses: [192.168.24.22/24]
     addresses: [192.168.24.15/24]
     addresses: [192.168.24.11/24]
     addresses: [192.168.24.12/24]
     addresses: [192.168.24.23/24]
     addresses: [192.168.24.24/24]
     addresses: [192.168.24.16/24]
     addresses: [192.168.24.25/24]
     addresses: [192.168.24.26/24]
     addresses: [192.168.24.27/24]
     gateway4: 192.168.24.253
     nameservers:
       addresses: [8.8.8.8,4.2.2.2]

Same problem

**Comment by nexusofdoom** [comment]
what does the /etc/hosts file look like.

**Comment by RobertJamesMichael** [comment]
like this:

# The following lines are desirable for IPv6 capable hosts
# ::1     localhost ip6-localhost ip6-loopback
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters

127.1.0.1       lancache-origin-backend
127.1.0.2       lancache-blizzard-backend

#This is the primary IP (of the network card / eth) that your Lancache is using
192.168.24.10 lancache-eth

#The Following are Virtual IP's used by Lancache
192.168.24.20 lancache-steam
192.168.24.202 lancache-steam2
192.168.24.203 lancache-steam3
192.168.24.204 lancache-steam4
192.168.24.205 lancache-steam5
192.168.24.206 lancache-steam6
192.168.24.207 lancache-steam7
192.168.24.208 lancache-steam8
192.168.24.209 lancache-steam9
192.168.24.2010 lancache-steam10
192.168.24.19 lancache-riot
192.168.24.13 lancache-blizzard
192.168.24.14 lancache-hirez
192.168.24.18 lancache-origin
192.168.24.21 lancache-sony
192.168.24.17 lancache-microsoft
192.168.24.22 lancache-enmasse
192.168.24.15 lancache-gog
192.168.24.11 lancache-arenanetworks
192.168.24.12 lancache-apple
192.168.24.23 lancache-wargaming
192.168.24.24 lancache-uplay
192.168.24.16 lancache-glyph
192.168.24.25 lancache-zenimax
192.168.24.26 lancache-digitalextremes
192.168.24.27 lancache-pearlabyss

**Comment by nexusofdoom** [comment]
if you can reload and re-run the installer I did make a change to the installer.

Thanks

**Comment by RobertJamesMichael** [comment]
NetPLan is:

network:
 version: 2
 renderer: networkd
 ethernets:
   ens33:
     dhcp4: no
     dhcp6: no
     addresses: [192.168.24.10/24]
     addresses: [192.168.24.20/24]
     addresses: [192.168.24.20/24A]
     addresses: [192.168.24.20/24B]
     addresses: [192.168.24.20/24C]
     addresses: [192.168.24.20/24D]
     addresses: [192.168.24.20/24E]
     addresses: [192.168.24.20/24F]
     addresses: [192.168.24.20/24G]
     addresses: [192.168.24.20/24H]
     addresses: [192.168.24.20/24I]
     addresses: [192.168.24.19/24]
     addresses: [192.168.24.13/24]
     addresses: [192.168.24.14/24]
     addresses: [192.168.24.18/24]
     addresses: [192.168.24.21/24]
     addresses: [192.168.24.17/24]
     addresses: [192.168.24.22/24]
     addresses: [192.168.24.15/24]
     addresses: [192.168.24.11/24]
     addresses: [192.168.24.12/24]
     addresses: [192.168.24.23/24]
     addresses: [192.168.24.24/24]
     addresses: [192.168.24.16/24]
     addresses: [192.168.24.25/24]
     addresses: [192.168.24.26/24]
     addresses: [192.168.24.27/24]
     gateway4: 192.168.24.253
     nameservers:
       addresses: [8.8.8.8,4.2.2.2]

And hosts (from line 16 ahead):
192.168.24.20 lancache-steam
192.168.24.20A lancache-steamA
192.168.24.20B lancache-steamB
192.168.24.20C lancache-steamC
192.168.24.20D lancache-steamD
192.168.24.20E lancache-steamE
192.168.24.20F lancache-steamF
192.168.24.20G lancache-steamG
192.168.24.20H lancache-steamH
192.168.24.20I lancache-steamI
192.168.24.19 lancache-riot
192.168.24.13 lancache-blizzard
192.168.24.14 lancache-hirez
192.168.24.18 lancache-origin
192.168.24.21 lancache-sony
192.168.24.17 lancache-microsoft
192.168.24.22 lancache-enmasse
192.168.24.15 lancache-gog
192.168.24.11 lancache-arenanetworks
192.168.24.12 lancache-apple
192.168.24.23 lancache-wargaming
192.168.24.24 lancache-uplay
192.168.24.16 lancache-glyph
192.168.24.25 lancache-zenimax
192.168.24.26 lancache-digitalextremes
192.168.24.27 lancache-pearlabyss

**Comment by nexusofdoom** [comment]
still working on this I will post update one I have the working installer for the new steam IP's

**Comment by nexusofdoom** [comment]
some of what I am working on 

while grep -q "lc-host-${service}" "${lc_tmp_hosts}" >> /dev/null
do


sed  -i '0,/lc-host-'$service'/s//'$lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4'/' "$lc_tmp_hosts"

**Comment by nexusofdoom** [comment]
for service in ${lc_services[@]}; do
	# Check if the folder exists if not creates it
	if [[ ! -d "/tmp/data/$service" ]]; then
		mkdir -p /tmp/data/$service
	fi

	#new stuff TTE - CARl LOOP
	while grep -q "lc-host-${service}" "${lc_tmp_hosts}" >> /dev/null
	do

		# Increases the IP with Every Run
		lc_ip_p4=$(expr $lc_ip_p4 + 1)
		# This for Netplan later on
	    echo $lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4/$lc_ip_sn >> "$lc_tmp_ip"
		
		sed  -i '0,/lc-host-'$service'/s//'$lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4'/' "$lc_tmp_unbound"

		sed  -i '0,/lc-host-'$service'/s//'$lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4'/' "$lc_tmp_hosts"
# need to test more
		#sed -i '0,/lc-host-'$service'/s//'$lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4'/' "$lc_tmp_yaml"
		sed -i '0,/lc-host-'$service'/s//'$lc_ip_p1.$lc_ip_p2.$lc_ip_p3.$lc_ip_p4'\/'$lc_ip_sn'/' $lc_tmp_yaml
	
	done



## for the unbound needing to update more then one steam and match the IP's collected in hosts file.

while (Fetch a lines in lc_tmp_hosts which match "lancache-steam") keep doing this until none is left
(clean line ends of space/etc)
Break split line by space. Line[0] is address.. Line[1] is varbile name

Search file lc_tmp_unbound for string Line[1] and repalce with Line[1]
done

**Comment by nexusofdoom** [comment]
the new installer should fix this issue.
