### ISSUE TITLE
lancache-steam.conf preventing nginx from starting

### ISSUE THREAD

**Issue by bureji25** [nexusofdoom/lancache-installer#35]
Finally got my lancache working, however I wasn't able to get ngnix started until I disabled the steam conf from loading. I was getting the following error message:

nginx: [emerg] host not found in "lancache-steam" of the "listen" directive in /etc/nginx/sites-available/test.lancache-steam.conf:2

Renaming lancache-steam.conf allowed nginx to start and bypass this issue, and it seems to be working with Blizzard now.

On a side note, I wasn't able to get unbound to start on Ubuntu 18.04 until I edited the following in /etc/systemd/resolved.conf:

#DNSStubListener=no

Please let me know if you can figure out what's up with lancache-steam.conf and if you need more info.

**Comment by bureji25** [comment]
Minor success; added "-ip address here- lancache-steam" at the top of /cat/hosts and steam seems to be working now, however I have a feeling that this is a bandaid and doesn't fix the whole problem

**Comment by nexusofdoom** [comment]
I am working on this 
IP Adresses #34

that will generate more ip's needed for steam.

**Comment by nexusofdoom** [comment]
also working on current domains that steam is using 
cache11-ord1.steamcontent.com it looks like cache1 - 15 on that domain name

**Comment by nexusofdoom** [comment]
the new installer should work for you.
