### ISSUE TITLE
Debian 9.5 without net-tools

### ISSUE THREAD

**Issue by Fischje** [nexusofdoom/lancache-installer#5]
Only want to make a notice on this project that on debian 9.5 there is no net-tools, so you can't use 
`ifconfig`

**Comment by nexusofdoom** [comment]
yep fun stuff. 
trying to rework for Ubuntu 18.04.1 and come back and make it work for the newer version of Debian

**Comment by nexusofdoom** [comment]
this is some of the things working on 
https://websiteforstudents.com/configure-static-ip-addresses-on-ubuntu-18-04-beta/

**Comment by nexusofdoom** [comment]
at this point the installer will work with ubuntu 18.04.1
